# cikmis_sorular.py

# Geçmiş yıllarda çıkmış sorulardan derlenen hap bilgiler
# Bu modül, uygulama içinde kullanıcıların erişimine sunulmak üzere hazırlanmıştır.

HAP_BILGILER = [
    "Mustafa Kemal'in askeri eğitim gördüğü şehirler: Manastır (Askerî İdadi) ve İstanbul (Harp Okulu/Akademisi).",
    "Mustafa Kemal'in ataşemiliterlik yaptığı şehir: Sofya.",
    "Mustafa Kemal'e 'Gazi' unvanı ve 'Mareşal' rütbesi verilen savaş: Sakarya Meydan Muharebesi.",
    "I. Dünya Savaşı'nı bitiren ve Bulgaristan ile imzalanan antlaşma: Nöyyi Antlaşması.",
    "Pozantı Kongresi'ni düzenleyen cemiyet: Kilikyalılar Cemiyeti.",
    "Milli Mücadele'de İtalyanların Anadolu'dan tamamen çekildiği savaş: Sakarya Meydan Muharebesi sonu (ve Büyük Taarruz süreci).",
    "Denizcilik alanındaki millileştirme kanunu: Kabotaj Kanunu.",
    "Orta Asya'dan Avrupa'ya göç etmeyen Türk topluluğu: Uygurlar.",
    "Türkiye Selçuklu başkentinin İznik'ten Konya'ya taşınma sebebi: I. Haçlı Seferi.",
    "Miryokefalon Savaşı'nı kazanan sultan: II. Kılıç Arslan.",
    "Kanuni Sultan Süleyman döneminde olmayan gelişme: Kıbrıs'ın Fethi (II. Selim dönemidir).",
    "Osmanlı'nın Avrupa devletler hukukundan yararlanma hakkı kazandığı antlaşma: Paris Antlaşması (1856).",
    "Halifelerin Türk hükümdarlarına gönderdiği hakimiyet sembolü elbise: Hilat.",
    "Sahn-ı Seman Medresesi'ni açan padişah: Fatih Sultan Mehmet.",
    "Şura-yı Devlet'in günümüzdeki karşılığı: Danıştay.",
    "Tevhid-i Tedrisat Kanunu'nun ilgili olduğu alan: Eğitim.",
    "Doğu Roma İmparatorluğu'nu ortadan kaldıran padişah: II. Mehmet (Fatih).",
    "Osmanlı ile Safeviler arasındaki antlaşmalardan biri olmayan: Zitvatorok (Avusturya ile yapılmıştır).",
    "'93 Harbi' olarak bilinen savaş: 1877-1878 Osmanlı-Rus Savaşı.",
    "Türklerde ilk düzenli orduyu kuran: Mete Han.",
    "Nizamülmülk'ün eseri: Siyasetname.",
    "Büyük Selçuklu'da belediye işlerine bakan görevli: Muhtesip.",
    "Osmanlı'da 'Ekber ve Erşed' sistemine geçen padişah: I. Ahmet.",
    "Çocuk Hizmetleri Genel Müdürlüğü'nün temelini oluşturan kurum: Himaye-i Etfal Cemiyeti.",
    "Mustafa Kemal'in 'Müdafaa-i Hukuk Grubu' yerine kurulan grup: Felah-ı Vatan Grubu.",
    "Sakarya Savaşı'nın diplomatik sonuçları: Ankara Antlaşması ve Kars Antlaşması.",
    "Medine Müdafaası kahramanı 'Çöl Kaplanı': Ömer Fahrettin (Türkkan) Paşa.",
    "Preveze Deniz Zaferi'nin kazanıldığı yer (Preveze): Günümüzde Yunanistan sınırlarındadır.",
    "Kutadgu Bilig'in yazarı: Yusuf Has Hacip.",
    "Nizamiye Medreselerini kuran devlet: Büyük Selçuklu Devleti.",
    "Ahilik teşkilatının Osmanlı'daki devamı: Lonca.",
    "Osmanlı'da mali işlerden sorumlu divan üyesi: Defterdar.",
    "İlk Türk devletlerinde hükümdarlık sembolü olmayan: Kalkan (Otağ, Davul, Tuğ, Kılıç semboldür).",
    "Mısır'da kurulan Türk devletlerinden olmayan: Gazneliler ve Osmanlılar (Osmanlı Mısır'ı yönetmiştir ama merkez Mısır değildir; Gazneliler Mısır'da kurulmamıştır).",
    "Kudüs'ü Haçlılardan geri alan komutan: Selahaddin Eyyubi.",
    "Türkiye'nin en kuzey ucu: İnceburun (Sinop).",
    "Endemik 'sığla ağacı'nın görüldüğü yer: Köyceğiz Gölü çevresi.",
    "Pamuk üretiminde öne çıkan il: Şanlıurfa.",
    "Linyit ile çalışan termik santral (Doğalgaz olmayan): Soma (Manisa).",
    "Kelebekler Vadisi Kanyonu hangi ilimizdedir? Muğla.",
    "Yeşilırmak Havzası Gelişim Projesi (YHGP) illerinden biri: Tokat (Amasya, Çorum, Samsun).",
    "Marmara Gölü hangi ilimizdedir? Manisa.",
    "Türkiye'nin gerçek yüzölçümü: Yaklaşık 814.578 km².",
    "Türkiye nüfus özelliği yanlışı: Erkek nüfus kadın nüfustan fazladır (Genelde dengelidir veya çok az fark vardır, ancak sorularda 'Tarım sektöründe istihdam en fazladır' ifadesi genellikle yanlış cevap olarak verilir, çünkü hizmet sektörü öndedir).",
    "Belen Geçidi hangi dağlar üzerindedir? Nur (Amanos) Dağları.",
    "Jeotermal enerjiden elektrik üretilen yerler: Sarayköy (Denizli) ve Germencik (Aydın).",
    "Ege'ye dökülen akarsuların kuzeyden güneye sırası: Bakırçay - Gediz - Küçük Menderes - Büyük Menderes.",
    "Hinterlandı dar olduğu için az gelişen liman şehri: Sinop.",
    "Petrol rafinerisi olmayan il: Adıyaman (Petrol çıkarılır ama rafineri yoktur; Batman, İzmit, Kırıkkale, İzmir'de vardır).",
    "Güney Marmara'da yer alan göl: Ulubat (veya Kuş) Gölü.",
    "Volkanik dağ örneği: Erciyes Dağı.",
    "Kaynağı dışarıda olup Türkiye'den denize dökülen akarsu: Asi Nehri (Kaynağı Lübnan/Suriye, döküldüğü yer Hatay/Türkiye).",
    "Memurun disiplin cezaları: Uyarma, Kınama, Aylıktan Kesme, Kademe İlerlemesinin Durdurulması, Devlet Memurluğundan Çıkarma.",
    "'Görev sırasında amire sözle saygısızlık' cezası: Kınama (Bazı kaynaklarda fiilin ağırlığına göre değişebilir, sınavda şıkka göre Kınama veya Aylıktan Kesme sorulabilir. 657'ye göre 'Saygısız davranmak' Kınama; 'Sözle saygısızlık/hakaret' daha ağır olabilir. Bu soruda cevap şıkkı Kınama olarak işaretlenmiştir).",
    "'Amire hal ve hareketi ile saygısız davranmak': Kınama cezası.",
    "Aylıktan kesme cezasını gerektiren fiil: Hizmet içinde devlet memurunun itibar ve güven duygusunu sarsacak nitelikte davranışlarda bulunmak veya ticari faaliyette bulunmak.",
    "Yurt dışı görevinde hastalık izni süresi: Birer yıllık dönemlerde 90 günü geçerse görev sonlandırılır.",
    "Pasaport Kanunu'na göre diplomatik pasaport harcı: Harç veya resme tabi değildir.",
    "Pasaport sürelerini belirleyen makam: İçişleri Bakanlığı.",
    "TBMM Denetim Yolları: Yazılı Soru, Genel Görüşme, Meclis Araştırması, Meclis Soruşturması. (Gensoru kaldırılmıştır).",
    "Yönetmelik çıkarma yetkisi: Cumhurbaşkanı, Bakanlıklar ve Kamu Tüzel Kişileri.",
    "Normlar Hiyerarşisi (Üstten alta): Anayasa > Kanun (ve Milletlerarası Antlaşmalar) > Cumhurbaşkanlığı Kararnamesi > Yönetmelik.",
    "Sosyal ve Ekonomik Haklar: Eğitim hakkı, Sendika kurma, Ailenin korunması. (Mülkiyet hakkı 'Kişi Hakları' grubundadır) .",
    "Siyasi Haklar: Seçme ve seçilme, Dilekçe hakkı, Vatan hizmeti.",
    "Milletlerarası antlaşmaları onaylama yetkisi: Cumhurbaşkanı.",
    "Yurt dışında görevlendirilecek personel sınavı: Mesleki Yeterlilik Sınavı ve Temsil Yeteneği Sınavı (Mülakat).",
    "Pasaport Türleri: Diplomatik (Siyah), Hususi (Yeşil), Hizmet (Gri), Umuma Mahsus (Bordo). Mavi pasaport artık kullanılmamaktadır.",
    "Mecburi ilköğretim çağı: 6-14 yaş (Ancak 222 sayılı kanuna göre öğretim yılı sonuna kadar bitiremeyenlere en çok 2 yıl daha izin verilir).",
    "Eğitime ara verme (Olağanüstü hal): En az 2 hafta yapılamazsa tatilde telafi edilebilir (izinler kısaltılabilir).",
    "Öğretim İlkeleri: Karmaşık bir konuyu anlaşılır dille anlatmak: Açıklık.",
    "Öğretim İlkeleri: Alışveriş yaparak matematik öğretmek: Yaşama Yakınlık (Hayatilik).",
    "Öğretim İlkeleri: Öğrenci ilgisini çekmeyen materyal kullanımı hatası: Öğrenciye Görelik.",
    "Öğretim Yöntem ve Teknikleri: Sanal ortamda/riskli durumlarda (askeri, pilot, sürücü) eğitim: Benzetim (Simülasyon).",
    "Öğretim Yöntem ve Teknikleri: Üst sınıfın alt sınıfa ders çalıştırması: Tutor (Akran) Destekli Öğretim.",
    "Öğretim Yöntem ve Teknikleri: Fikirlerin saçma/doğru ayrımı yapılmadan listelenmesi: Beyin Fırtınası.",
    "Öğretim Yöntem ve Teknikleri: Bir işi başlatıp diğer grubun devam ettirmesi (şiir, poster vb.): İstasyon.",
    "Öğretim Yöntem ve Teknikleri: Konunun uzmanlarca sunulup sonunda soru alınması (bilimsel): Sempozyum (Bilgi Şöleni).",
    "Öğretim Yöntem ve Teknikleri: Tez-Antitez savunması (Jüri önünde): Münazara.",
    "Öğretim Yöntem ve Teknikleri: Öğrencinin kendi kendine ilke ve genellemelere ulaştığı yol: Buluş Yoluyla Öğretim.",
    "Düşünme Becerileri: Hatalardan ders çıkarma, öz eleştiri: Yansıtıcı Düşünme.",
    "Düşünme Becerileri: Olaylara farklı açılardan bakma (Şapkalar): Altı Şapkalı Düşünme. (Sarı şapka: İyimser/Olumlu).",
    "Düşünme Becerileri: Gerçek/Güvenilir bilgiyi sorgulama: Eleştirel Düşünme.",
    "Çoklu Zekâ: Yalnız yapamama, grupla/sohbetle öğrenme: Sosyal Zekâ.",
    "Çoklu Zekâ: El-göz koordinasyonu, yapma-etme (Berber örneği): Bedensel/Kinestetik Zekâ.",
    "Program Geliştirme: Eğitim programlarını hazırlama/karar organı: Talim ve Terbiye Kurulu Başkanlığı.",
    "Bayrağında hilal olmayan Türk Cumhuriyeti: Kırgızistan (Güneş vardır).",
    "Karabağ Zaferi ateşkes arabulucusu: Rusya.",
    '"Çöpçüler Kralı" filmindeki karakter: Apti.',
    "Uzaya çıkan ilk insan: Yuri Gagarin.",
    "Machu Picchu antik kenti: Peru.",
    "Hollywood (Sinema): ABD.",
    "2020 Tokyo Olimpiyatları'nda Türkiye'nin en çok madalya aldığı branş: Karate.",
    "Türkiye'nin yurt dışı kültür tanıtım kurumu (2007): Yunus Emre Enstitüsü.",
    "Mona Lisa tablosunun bulunduğu şehir: Paris (Louvre Müzesi).",
    "Almanya Hükümet Başkanı unvanı: Şansölye.",
    "e-Devlet Kapısı yöneticisi: Cumhurbaşkanlığı Dijital Dönüşüm Ofisi.",
    "Mars keşif aracı (NASA): Perseverance.",
    "ABD'deki 'Türkevi' binası: New York.",
    "Pinokyo'nun ait olduğu edebiyat: İtalya.",
    "Küçük Prens'in adandığı kişi: Yazarın arkadaşı (Leon Werth).",
    "Öldürülen The Beatles üyesi: John Lennon.",
    "Muhammed Ali'nin gitmeyi reddettiği savaş: Vietnam Savaşı.",
    "Grand Slam (Tenis) turnuvası olmayan: İspanya Açık (Avustralya, Fransa, Wimbledon, ABD vardır).",
    "Hem futbol hem basketbol milli olan sporcu: Can Bartu.",
    "Orhun Yazıtları'nın kaidesi: Kaplumbağa.",
    "Looney Tunes karakteri olmayan: Tom ve Jerry (MGM yapımıdır).",
    "24 Kasım Öğretmenler Günü nedeni: Atatürk'e 'Başöğretmen' unvanının verilmesi.",
    "Resim sanatı temsilcileri: Şeker Ahmet Paşa, Osman Hamdi Bey.",
    "Avrupa İnsan Hakları Mahkemesi (AİHM) yargıç sayısı: Taraf devlet sayısı kadardır (Her devletten bir yargıç).",
    "BM Yargı Organı: Uluslararası Adalet Divanı (Lahey).",
    "J.R.R. Tolkien'in eseri: Yüzüklerin Efendisi.",
    "Dönüşüm (Gregor Samsa) yazarı: Franz Kafka.",
    "Türk Lirası uluslararası kodu: TRY.",
    "Dünya Engelliler Günü: 3 Aralık.",
    "Osmanlı'daki ilk borsa: Dersaadet Tahvilat Borsası.",
    "Kobe Bryant'ın efsaneleştiği şehir/takım: Los Angeles (Lakers).",
    "1918-1920 Küresel Salgın: İspanyol Gribi.",
    "TEMA Vakfı kurucusu ('Toprak Dede'): Hayrettin Karaca.",
    "İlk yerli baz istasyonu: Ulak.",
    "2019 Nobel Barış Ödülü: Abiy Ahmed Ali (Etiyopya).",
    "Vatanım Sensin / Filinta / Payitaht Abdülhamid: Tarihî kurgu dizileridir (Payitaht: II. Abdülhamid dönemi).",
]

def get_hap_bilgiler():
    """Hap bilgileri döndürür."""
    return HAP_BILGILER
